sudo: required
dist: trusty

language: node_js

node_js:
  - "node"

cache:
  directories:
    - test/elm-stuff/build-artifacts

os:
  - linux

before_install:
  - npm install -g elm
  - npm install -g elm-test

install:
  - node --version
  - npm --version

script: elm test
